default: &default
  adapter: postgresql
  encoding: 'utf8'
  pool: 5
  port: 5432
  host: 'localhost'

development:
  <<: *default
  database: atelier_development

test:
  <<: *default
  database: atelier_test

production:
  <<: *default
  database: atelier_production
